Us102 modification seed
WildCodeSchool/Lyon-JS-09-23-P3-mechka-food pull request #104
Opened 2024-02-05 19:20 UTC by Bak-Faek

ajout de plusieurs entrée dans le fichier seed

2024-02-05 19:23 UTC, axelarese approved these changes

2024-02-05 19:27 UTC, wildmatthieu requested changes

2024-02-05 19:27 UTC, wildmatthieu commented on backend/seed.js
> +            ('Salade de Quinoa aux Légumes Grillés', 'Cette salade fraîche et nourrissante associe du quinoa tendre avec des légumes grillés, offrant une explosion de saveurs et de textures. Parfait
image qui pointent vers des serveurs externes, à remplacer par des images en local  (et libres de droits)

2024-02-05 19:27 UTC, wildmatthieu commented on backend/seed.js
> +            ('Soupe aux champignons crémeuse', "Cette soupe aux champignons crémeuse est un régal réconfortant pour les jours frais. Des champignons de Paris frais sautés dans du beurre, mélangés à d
image qui pointent vers des serveurs externes, à remplacer par des images en local  (et libres de droits)

2024-02-05 19:27 UTC, wildmatthieu commented on backend/seed.js
> +            ("Salade de chèvre chaud", "Une salade fraîche et savoureuse qui marie la douceur du fromage de chèvre chaud avec la fraîcheur des légumes verts et la douceur des fruits secs.", "25 minut
image qui pointent vers des serveurs externes, à remplacer par des images en local  (et libres de droits)

2024-02-06 02:20 UTC, Bak-Faek commented on backend/seed.js
> +            ('Salade de Quinoa aux Légumes Grillés', 'Cette salade fraîche et nourrissante associe du quinoa tendre avec des légumes grillés, offrant une explosion de saveurs et de textures. Parfait
images ajoutées en local et libres de droit

2024-02-06 02:21 UTC, Bak-Faek commented on backend/seed.js
> +            ("Salade de chèvre chaud", "Une salade fraîche et savoureuse qui marie la douceur du fromage de chèvre chaud avec la fraîcheur des légumes verts et la douceur des fruits secs.", "25 minut
images ajoutées en local et libres de droit

2024-02-06 02:21 UTC, Bak-Faek commented on backend/seed.js
> +            ('Soupe aux champignons crémeuse', "Cette soupe aux champignons crémeuse est un régal réconfortant pour les jours frais. Des champignons de Paris frais sautés dans du beurre, mélangés à d
images ajoutées en local et libres de droit

2024-02-06 09:17 UTC, merged